name: Build and Test .NET Todo App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'  # Use latest patch of .NET 9

      - name: Restore Dependencies
        run: dotnet restore ToDoApp.sln
        working-directory: ./Web API

      - name: Build Project
        run: dotnet build ToDoApp.sln --configuration Release
        working-directory: ./Web API

      - name: Run Tests
        run: dotnet test ToDoApp.sln --configuration Release --no-build --verbosity normal
        working-directory: ./Web API
